---

- name: Installing packages
  apt:
    pkg: "unattended-upgrades"
    state: "{{ 'latest' if apt_unattended_upgrades else 'absent' }}"
  when: apt_unattended_upgrades

- name: Configure unattended-upgrades
  template:
    src: "{{ item }}.j2"
    dest: "/{{ item }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - "etc/apt/apt.conf.d/25auto-upgrades.conf"
    - "etc/apt/apt.conf.d/50unattended-upgrades.conf"
  when: apt_unattended_upgrades
